### ISSUE TITLE
new line in test description hangs junit runner in eclipse

### ISSUE THREAD

**Issue by mikosik** [quackery/quackery#38]
Junit runner in eclipse will hang forever when running following test:

```
@RunWith(QuackeryRunner.class)
public class MyTest {
  @Quackery
  public static Case hangsForever() {
    return Case.newCase("\n", () -> {});
  }
}
```

screenshot from eclipse

![image](https://cloud.githubusercontent.com/assets/4783806/13550077/6202cb54-e315-11e5-9e87-f42b643e7d1b.png)

**Comment by mikosik** [comment]
The same is also true for `\r`.

**Comment by maciejmikosik** [comment]
This is similar to #25 Empty suite confuses junit.
Similarly, let's verify if the same problem occurs in intellij.
If so, then we can implement workaround in `QuackeryRunner`.

**Comment by maciejmikosik** [comment]
It look that intellij 14.1.5 behaves correctly by removing formatting characters and printing test name in one line.

**Comment by maciejmikosik** [comment]
implemented workaround for eclipse bug displaying newline characters 7858f8b6cba00d89d72b187b35e323d62251ef3f
